GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
	"text": "Lets get good at sports betting on baseball"
}

###

DELETE http://localhost:3001/todo/delete/64850b8807aadfd8075a5660

###

PUT http://localhost:3001/todo/complete/64850b4107aadfd8075a565d